name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Docker
        run: |
          sudo docker build -t my-html-app .
          sudo docker stop my-html-container || true
          sudo docker rm my-html-container || true
          sudo docker run -d -p 80:80 --name my-html-container my-html-app
